### ISSUE TITLE
你好，可以使用你的包含四级词汇的json文件吗

### ISSUE THREAD

**Issue by XiaochenCui** [kasuganosora/moxie#1]
[文件](https://github.com/kasuganosora/moxie/blob/master/www/dict/%E5%9B%9B%E7%BA%A7%E8%80%83%E8%AF%95%E9%AB%98%E9%A2%91%E8%AF%8D%E6%B1%87.json)

**Comment by kasuganosora** [comment]
可以 我忘记是什么地方离搞来的。。
